language: cpp
compiler:
  - gcc
  - clang
before_install: sudo apt-get update -qq
install:
  - sudo apt-get install -qq libopencv-dev
  - sudo pip install cpp-coveralls
before_script:
  - mkdir ./build
  - cd ./build
script:
  - cmake -DWITH_CODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../photoeffects
  - make -j5
  - cd ./bin/
  - ./photoeffects_test
after_success:
  - cd ../
  - coveralls --exclude photoeffects/3rdparty --exclude photoeffects/test --exclude photoeffects/samples --exclude photoeffects/testdata --exclude photoeffects/docs --exclude build/CMakeFiles --exclude build/samples --exclude build/3rdparty --exclude build/bin --exclude build/lib --root ../ --build-root ./
notifications:
  email: false
