language: cpp
compiler:
  - gcc
  - clang
before_install:
  - mkdir ../opencv/
  - cd ../opencv/
  - wget http://sourceforge.net/projects/opencvlibrary/files/latest/download
  - unzip download
  - mkdir build-opencv
  - cd ./build-opencv/
install:
  - cmake ../opencv-2.4.9/
  - make opencv_imgproc opencv_highgui opencv_ts opencv_core
  - sudo make install
before_script:
  - mkdir ../../build
  - cd ../../build
script:
  - cmake ../itlab-vision/photoeffects
  - make -j5
  - cd ./bin/
  - ./photoeffects_test
notifications:
  email: false
