language: cpp
compiler:
  - gcc
  - clang
before_install: sudo apt-get update -qq
install:
  - sudo apt-get install kwstyle
  - sudo apt-get install -qq libopencv-dev
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../itlab-vision/photoeffects
  - make -j5
  - cd ./bin/
  - ./photoeffects_test
  - cd ../../itlab-vision
  - KWStyle -v -D Files.txt 
notifications:
  email: false
