language: cpp
compiler:
  - gcc
  - clang
before_install:
  - cd ../
  - wget http://sourceforge.net/projects/opencvlibrary/files/latest/download
  - mkdir opencv
  - unzip opencv-2.4.9.zip -d opencv
  - mkdir build-opencv
  - cd ./build-opencv/
install:
  - cmake ../opencv/
  - make -j5
  - make install
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../itlab-vision/photoeffects
  - make -j5
  - cd ./bin/
  - ./photoeffects_test
notifications:
  email: false
