language: cpp
compiler:
  - gcc
  - clang
before_install:
  - cd ../
  - wget http://sourceforge.net/projects/opencvlibrary/files/latest/download
  - unzip opencv-2.4.9.zip
  - mkdir build-opencv
  - cd ./build-opencv/
install:
  - cmake ../opencv-2.4.9/
  - make -j5
  - sudo make install
before_script:
  - mkdir ./build
  - cd ./build
script:
  - cmake -DWITH_CODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../photoeffects
  - make -j5
  - cd ./bin/
  - ./photoeffects_test
after_success:
  - cd ../
  - coveralls --exclude photoeffects/3rdparty --exclude photoeffects/test --exclude photoeffects/samples --exclude photoeffects/testdata --exclude photoeffects/docs --exclude build/CMakeFiles --exclude build/samples --exclude build/3rdparty --exclude build/bin --exclude build/lib --root ../ --build-root ./
notifications:
  email: false
