set(TBB_DEFAULT_INCLUDE_DIRS
  "/opt/intel/tbb/include" "/usr/local/include" "/usr/include" "${CMAKE_INSTALL_PREFIX}/include")
find_path(TBB_INCLUDE_DIRS "tbb/tbb.h" PATHS ${TBB_INCLUDE_DIR} ${TBB_DEFAULT_INCLUDE_DIRS} DOC "The path to TBB headers")

if(TBB_INCLUDE_DIRS)
  if(UNIX)
    set(TBB_LIB_DIR "${TBB_INCLUDE_DIRS}/../lib" CACHE PATH "Full path of TBB library directory")
  else()
    set(TBB_LIB_DIR "" CACHE PATH "Full path of TBB library directory")
  endif()
  if(NOT TBB_LIB_DIR)
    message(FATAL_ERROR "TBB_LIB_DIR is not found")
  endif()
  link_directories("${TBB_LIB_DIR}")

  if(APPLE)
    set(LIBRARY_DEPS ${LIBRARY_DEPS} libtbb.dylib)
  else()
    set(LIBRARY_DEPS ${LIBRARY_DEPS} tbb)
  endif()
  set(HAVE_TBB 1)
else()
  message(FATAL_ERROR "TBB is not found")
endif()
